# This file was generated by GoReleaser. DO NOT EDIT.
class Venona < Formula
  desc "venona --help"
  homepage "http://docs.codefresh.io"
  version "0.28.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/codefresh-io/venona/releases/download/v0.28.0/venona_0.28.0_Darwin_x86_64.tar.gz"
    sha256 "87cca01be4998cdf5db03b69fe18fa5da3b107018cb86c8b7349bb51527d78a5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/codefresh-io/venona/releases/download/v0.28.0/venona_0.28.0_Linux_x86_64.tar.gz"
      sha256 "282003405a40cc1613df8711f97d5a2f36dc71761acfb9e87953dcb0e52466da"
    end
  end

  def install
    bin.install "venona"
  end
end
