# This file was generated by GoReleaser. DO NOT EDIT.
class Venona < Formula
  desc "venona --help"
  homepage "http://docs.codefresh.io"
  version "0.29.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/codefresh-io/venona/releases/download/v0.29.1/venona_0.29.1_Darwin_x86_64.tar.gz"
    sha256 "0a023ddca48d2c790ae244ab8186c899d7ad32aa6d45e698e8a18b8054f2d369"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/codefresh-io/venona/releases/download/v0.29.1/venona_0.29.1_Linux_x86_64.tar.gz"
      sha256 "cbefab131612900ea2c1fe0f7156e70b9c3a11105283b86cd71592fed9f90277"
    end
  end

  def install
    bin.install "venona"
  end
end
